In [3]:
from utils.dataset.dataset_concat import dataset_concat

In [ ]:
threshold_dollar = 29200152 # for aprox 15 minutes
dataset_concat(path='./dataset', bar_type="dollar", threshold=threshold_dollar, output_file_path='./dataset/btc-01_2025-09-2025-dollar-15min/btc-01_2025-09-2025-dollar-15min.csv')

In [4]:
threshold_volume = 290 # for aprox 15 minutes
dataset_concat(path='./dataset', bar_type="volume", threshold=threshold_volume, output_file_path='./dataset/btc-01_2025-09-2025-volume-15min/btc-01_2025-09-2025-volume-15min.csv')

,date_time,tick_num,open,high,low,close,volume,cum_buy_volume,cum_ticks,cum_dollar_value
0,2025-01-01 00:32:32.519130+00:00,46273,93576.00,93940.00,93489.03,93940.00,290.05130,128.99844,46273,2.717276e+07
1,2025-01-01 00:57:57.067039+00:00,82520,93940.00,94330.59,93836.61,94320.00,290.12551,208.66780,36247,2.729984e+07
2,2025-01-01 01:05:28.341289+00:00,109125,94320.00,94509.42,93997.86,94000.00,292.83859,156.24683,26605,2.760956e+07
3,2025-01-01 01:31:56.527742+00:00,143810,94000.00,94172.00,93819.60,93947.67,292.12049,130.53835,34685,2.744654e+07
4,2025-01-01 02:16:23.680412+00:00,195758,93947.67,93978.18,93578.77,93753.02,290.00191,144.23861,51948,2.719289e+07
...,...,...,...,...,...,...,...,...,...,...
19681,2025-09-30 20:54:56.617205+00:00,64380826,114170.43,114698.99,114170.43,114698.99,290.00653,190.29361,53089,3.318874e+07
19682,2025-09-30 21:13:07.644125+00:00,64422962,114698.99,114754.87,114509.55,114524.01,290.06525,157.70103,42136,3.326716e+07
19683,2025-09-30 21:39:52.695186+00:00,64483171,114524.02,114534.68,114206.56,114454.71,290.03646,126.93619,60209,3.317773e+07
19684,2025-09-30 22:17:37.225629+00:00,64556360,114454.71,114454.72,114120.19,114162.78,290.03470,93.75792,73189,3.313950e+07
19685,2025-09-30 23:12:57.728052+00:00,64618989,114162.78,114174.35,113765.42,113802.53,290.03986,112.75638,62629,3.305197e+07

In [5]:
threshold_tick = 45680.0 # for aprox 15 minutes
dataset_concat(path='./dataset', bar_type="tick", threshold=threshold_tick, output_file_path='./dataset/btc-01_2025-09-2025-tick-15min/btc-01_2025-09-2025-tick-15min.csv')

,date_time,tick_num,open,high,low,close,volume,cum_buy_volume,cum_ticks,cum_dollar_value
0,2025-01-01 00:32:17.079847+00:00,45680,93576.00,93920.00,93489.03,93920.00,287.02962,126.06876,45680,2.688892e+07
1,2025-01-01 00:59:15.685255+00:00,91360,93920.00,94509.42,93836.61,94445.71,462.52080,338.41250,45680,4.357197e+07
2,2025-01-01 01:26:24.346744+00:00,137040,94444.02,94444.02,93850.39,93891.44,356.35527,136.69583,45680,3.350755e+07
3,2025-01-01 02:04:20.592846+00:00,182720,93891.44,93989.37,93578.77,93762.99,263.24075,107.73407,45680,2.469117e+07
4,2025-01-01 02:59:34.115586+00:00,228400,93762.99,94105.12,93674.02,94091.10,249.96017,165.89969,45680,2.346122e+07
...,...,...,...,...,...,...,...,...,...,...
19914,2025-09-30 21:29:09.425895+00:00,64454480,114727.04,114753.88,114341.83,114349.01,230.99958,108.07290,45680,2.646086e+07
19915,2025-09-30 21:47:23.475470+00:00,64500160,114349.00,114531.97,114206.56,114303.24,205.21373,83.58934,45680,2.346840e+07
19916,2025-09-30 22:08:17.786418+00:00,64545840,114303.24,114371.64,114136.50,114160.52,203.00621,72.54661,45680,2.319528e+07
19917,2025-09-30 22:47:48.116000+00:00,64591520,114160.52,114202.90,113883.01,113960.63,206.99261,74.21563,45680,2.360608e+07
19918,2025-09-30 23:32:47.020837+00:00,64637200,113960.90,114022.91,113765.42,113968.69,236.81142,121.77541,45680,2.697185e+07